"""empty message

Revision ID: 4ea760dc6160
Revises: None
Create Date: 2015-04-21 10:14:04.192427

"""

# revision identifiers, used by Alembic.
revision = '4ea760dc6160'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
